feat: support 'relative path' for client; build: refactor compiling arguments; misc: update shell scripts; doc: sync these changes;

diff --git a/scripts/wstp_daemon b/scripts/wstp_daemon
--- a/scripts/wstp_daemon
+++ b/scripts/wstp_daemon
@@ -1,27 +1,32 @@
 #!/usr/bin/env zsh
 
 if lsof -i :5000 >/dev/null 2>&1 && pgrep WolframKernel >/dev/null 2>&1; then
+    if [[ "$1" == "start" ]]; then
+        echo "INFO: wstp daemon is already running ..."
+        exit 1
+    fi
     if [[ "$1" == "kill" ]]; then
         kill -9 "$(lsof -t -i:5000)"
         echo "INFO: Wolframkernel has been killed ..."
         exit 0
-    else
-        if [ -z "$1" ]; then
-        else
-            echo "ERROR: wrong command '$1', use 'wstp_daemon kill' to kill it."
-            exit 1
-        fi
     fi
-    echo "wstp daemon is already running ..."
+
+    if [ -z "$1" ]; then
+        echo "INFO: wstp daemon is already running ..."
+        exit 1
+    else
+        echo "ERROR: wrong argument '$1', usage - 'wstp_daemon [start]|kill'"
+        exit 1
+    fi
 else
     if [[ "$1" == "start" || -z "$1" ]]; then
+        echo "INFO: launching Wolframkernel ..."
         wolfram -script "$HOME/Dependency/scripts/wstp_server.wls" > /dev/null 2>&1 &!
-        echo "INFO: Wolframkernel is listening port 5000 ..."
+        echo "INFO: Wolframkernel is listening for port 5000 ..."
+        exit 0
     else
-        if [ -z "$1" ]; then
-        else
-            echo "ERROR: wrong command '$1', use 'wstp_daemon [start]' to launch Wolframkernel."
-            exit 1
-        fi
+        echo "ERROR: wrong argument '$1', usage - 'wstp_daemon [start]|kill'"
+        echo "ERROR: use 'wstp_daemon [start]' to launch Wolframkernel first."
+        exit 1
     fi
 fi
