misc: refactor script 'wstp_daemon'; fix: typo in 'example.wls'.

diff --git a/scripts/wstp_daemon b/scripts/wstp_daemon
--- a/scripts/wstp_daemon
+++ b/scripts/wstp_daemon
@@ -1,23 +1,23 @@
 #!/usr/bin/env zsh
 
 if lsof -i :5000 >/dev/null 2>&1 && pgrep WolframKernel >/dev/null 2>&1; then
-    if [[ "$1" == "start" ]]; then
-        echo "INFO: wstp daemon is already running ..."
-        exit 1
-    fi
-    if [[ "$1" == "kill" ]]; then
-        kill -9 "$(lsof -t -i:5000)"
-        echo "INFO: Wolframkernel has been killed ..."
-        exit 0
-    fi
-
-    if [ -z "$1" ]; then
-        echo "INFO: wstp daemon is already running ..."
-        exit 1
-    else
-        echo "ERROR: wrong argument '$1', usage - 'wstp_daemon [start]|kill'"
-        exit 1
-    fi
+    echo "INFO: wstp daemon is already running ..."
+    case "$1" in
+        "")
+            exit 1
+            ;;
+        "start")
+            exit 1
+            ;;
+        "kill")
+            kill -9 "$(lsof -t -i:5000)"
+            exit 0
+            ;;
+        *)
+            echo "ERROR: wrong argument '$1', usage - 'wstp_daemon [start]|kill'"
+            exit 1
+            ;;
+    esac
 else
     if [[ "$1" == "start" || -z "$1" ]]; then
         echo "INFO: launching Wolframkernel ..."
@@ -25,7 +25,11 @@ else
         echo "INFO: Wolframkernel is listening for port 5000 ..."
         exit 0
     else
-        echo "ERROR: wrong argument '$1', usage - 'wstp_daemon [start]|kill'"
+        if [[ "$1" == "kill" ]]; then
+            echo "WARNING: inappropriate argument '$1'."
+        else
+            echo "ERROR: wrong argument '$1'."
+        fi
         echo "ERROR: use 'wstp_daemon [start]' to launch Wolframkernel first."
         exit 1
     fi
